# mysql.yml
apiVersion: v1
kind: Pod
metadata:
  name: mysql                # 생성될 파드의 이름
spec:
  containers:
    - name: mysql              # 컨테이너 이름
      image: mysql:8.0         # 사용할 도커 이미지 버전
      env:                     # MySQL 실행을 위한 필수 환경 변수 설정
        - name: MYSQL_ROOT_PASSWORD
          value: "root1234" # 루트 계정 비밀번호 설정
      volumeMounts:            # [연결 2] 컨테이너 내부와 볼륨 연결
        - name: mysql-storage     # 아래 'volumes'에서 정의한 이름과 일치해야 함
          mountPath: /var/lib/mysql # MySQL의 데이터가 실제로 저장되는 컨테이너 내부 경로

  volumes:                   # [연결 1] 외부 저장소 정의
    - name: mysql-storage      # 이 볼륨 설정의 고유 이름
      persistentVolumeClaim:   # PVC를 통해 스토리지를 가져오겠다고 선언
        claimName: pvc-mysql   # [핵심] 이미 생성된 'pvc-mysql' 요청서를 사용하여 스토리지 연결